// File generated from our OpenAPI spec by Stainless.

package io.nextbillion.api.models.navigation

import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import io.nextbillion.api.core.JsonValue
import io.nextbillion.api.core.jsonMapper
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class NavigationRetrieveRouteResponseTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val navigationRetrieveRouteResponse =
            NavigationRetrieveRouteResponse.builder()
                .msg("msg")
                .addRoute(
                    NavigationRetrieveRouteResponse.Route.builder()
                        .distance(0.0)
                        .distanceFull(0.0)
                        .duration(0L)
                        .endLocation(
                            NavigationRetrieveRouteResponse.Route.EndLocation.builder()
                                .latitude(0.0)
                                .longitude(0.0)
                                .build()
                        )
                        .geojson(
                            NavigationRetrieveRouteResponse.Route.Geojson.builder()
                                .geometry("geometry")
                                .properties("properties")
                                .type(NavigationRetrieveRouteResponse.Route.Geojson.Type.POINT)
                                .build()
                        )
                        .geometry("geometry")
                        .addLeg(
                            NavigationRetrieveRouteResponse.Route.Leg.builder()
                                .distance(
                                    NavigationRetrieveRouteResponse.Route.Leg.Distance.builder()
                                        .value(0L)
                                        .build()
                                )
                                .duration(
                                    NavigationRetrieveRouteResponse.Route.Leg.Duration.builder()
                                        .value(0L)
                                        .build()
                                )
                                .endLocation(
                                    NavigationRetrieveRouteResponse.Route.Leg.EndLocation.builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .rawDuration(JsonValue.from(mapOf<String, Any>()))
                                .startLocation(
                                    NavigationRetrieveRouteResponse.Route.Leg.StartLocation
                                        .builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .addStep(
                                    NavigationRetrieveRouteResponse.Route.Leg.Step.builder()
                                        .distance(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Distance
                                                .builder()
                                                .value(0L)
                                                .build()
                                        )
                                        .drivingSide("driving_side")
                                        .duration(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Duration
                                                .builder()
                                                .value(0L)
                                                .build()
                                        )
                                        .endLocation(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .EndLocation
                                                .builder()
                                                .latitude(0.0)
                                                .longitude(0.0)
                                                .build()
                                        )
                                        .geojson(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Geojson
                                                .builder()
                                                .geometry("geometry")
                                                .type("type")
                                                .build()
                                        )
                                        .geometry("geometry")
                                        .addIntersection(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .Intersection
                                                .builder()
                                                .addBearing(0L)
                                                .addClass("string")
                                                .addEntry(true)
                                                .intersectionIn(0L)
                                                .intersectionOut(0L)
                                                .addLane(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Intersection
                                                        .Lane
                                                        .builder()
                                                        .addIndication("string")
                                                        .valid(true)
                                                        .build()
                                                )
                                                .location(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Intersection
                                                        .Location
                                                        .builder()
                                                        .latitude(0.0)
                                                        .longitude(0.0)
                                                        .name("name")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .maneuver(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Maneuver
                                                .builder()
                                                .bearingAfter(0.0)
                                                .bearingBefore(0.0)
                                                .coordinate(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Maneuver
                                                        .Coordinate
                                                        .builder()
                                                        .latitude(0.0)
                                                        .longitude(0.0)
                                                        .name("name")
                                                        .build()
                                                )
                                                .instruction("instruction")
                                                .maneuverType("`turn`")
                                                .muted(true)
                                                .roundaboutCount(0L)
                                                .addVoiceInstruction(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Maneuver
                                                        .VoiceInstruction
                                                        .builder()
                                                        .distanceAlongGeometry(0L)
                                                        .instruction("instruction")
                                                        .unit("unit")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .reference("reference")
                                        .roadShieldType(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .RoadShieldType
                                                .builder()
                                                .imageUrl("image_url")
                                                .label("label")
                                                .build()
                                        )
                                        .startLocation(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .StartLocation
                                                .builder()
                                                .latitude(0.0)
                                                .longitude(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .predictedDuration(0.0)
                        .rawDuration(0.0)
                        .specialObjects(JsonValue.from(mapOf<String, Any>()))
                        .startLocation(
                            NavigationRetrieveRouteResponse.Route.StartLocation.builder()
                                .latitude(0.0)
                                .longitude(0.0)
                                .build()
                        )
                        .weight(0.0)
                        .build()
                )
                .status("status")
                .addWarning("string")
                .build()

        assertThat(navigationRetrieveRouteResponse.msg()).contains("msg")
        assertThat(navigationRetrieveRouteResponse.routes().getOrNull())
            .containsExactly(
                NavigationRetrieveRouteResponse.Route.builder()
                    .distance(0.0)
                    .distanceFull(0.0)
                    .duration(0L)
                    .endLocation(
                        NavigationRetrieveRouteResponse.Route.EndLocation.builder()
                            .latitude(0.0)
                            .longitude(0.0)
                            .build()
                    )
                    .geojson(
                        NavigationRetrieveRouteResponse.Route.Geojson.builder()
                            .geometry("geometry")
                            .properties("properties")
                            .type(NavigationRetrieveRouteResponse.Route.Geojson.Type.POINT)
                            .build()
                    )
                    .geometry("geometry")
                    .addLeg(
                        NavigationRetrieveRouteResponse.Route.Leg.builder()
                            .distance(
                                NavigationRetrieveRouteResponse.Route.Leg.Distance.builder()
                                    .value(0L)
                                    .build()
                            )
                            .duration(
                                NavigationRetrieveRouteResponse.Route.Leg.Duration.builder()
                                    .value(0L)
                                    .build()
                            )
                            .endLocation(
                                NavigationRetrieveRouteResponse.Route.Leg.EndLocation.builder()
                                    .latitude(0.0)
                                    .longitude(0.0)
                                    .build()
                            )
                            .rawDuration(JsonValue.from(mapOf<String, Any>()))
                            .startLocation(
                                NavigationRetrieveRouteResponse.Route.Leg.StartLocation.builder()
                                    .latitude(0.0)
                                    .longitude(0.0)
                                    .build()
                            )
                            .addStep(
                                NavigationRetrieveRouteResponse.Route.Leg.Step.builder()
                                    .distance(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.Distance
                                            .builder()
                                            .value(0L)
                                            .build()
                                    )
                                    .drivingSide("driving_side")
                                    .duration(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.Duration
                                            .builder()
                                            .value(0L)
                                            .build()
                                    )
                                    .endLocation(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.EndLocation
                                            .builder()
                                            .latitude(0.0)
                                            .longitude(0.0)
                                            .build()
                                    )
                                    .geojson(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.Geojson
                                            .builder()
                                            .geometry("geometry")
                                            .type("type")
                                            .build()
                                    )
                                    .geometry("geometry")
                                    .addIntersection(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.Intersection
                                            .builder()
                                            .addBearing(0L)
                                            .addClass("string")
                                            .addEntry(true)
                                            .intersectionIn(0L)
                                            .intersectionOut(0L)
                                            .addLane(
                                                NavigationRetrieveRouteResponse.Route.Leg.Step
                                                    .Intersection
                                                    .Lane
                                                    .builder()
                                                    .addIndication("string")
                                                    .valid(true)
                                                    .build()
                                            )
                                            .location(
                                                NavigationRetrieveRouteResponse.Route.Leg.Step
                                                    .Intersection
                                                    .Location
                                                    .builder()
                                                    .latitude(0.0)
                                                    .longitude(0.0)
                                                    .name("name")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .maneuver(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.Maneuver
                                            .builder()
                                            .bearingAfter(0.0)
                                            .bearingBefore(0.0)
                                            .coordinate(
                                                NavigationRetrieveRouteResponse.Route.Leg.Step
                                                    .Maneuver
                                                    .Coordinate
                                                    .builder()
                                                    .latitude(0.0)
                                                    .longitude(0.0)
                                                    .name("name")
                                                    .build()
                                            )
                                            .instruction("instruction")
                                            .maneuverType("`turn`")
                                            .muted(true)
                                            .roundaboutCount(0L)
                                            .addVoiceInstruction(
                                                NavigationRetrieveRouteResponse.Route.Leg.Step
                                                    .Maneuver
                                                    .VoiceInstruction
                                                    .builder()
                                                    .distanceAlongGeometry(0L)
                                                    .instruction("instruction")
                                                    .unit("unit")
                                                    .build()
                                            )
                                            .build()
                                    )
                                    .name("name")
                                    .reference("reference")
                                    .roadShieldType(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step
                                            .RoadShieldType
                                            .builder()
                                            .imageUrl("image_url")
                                            .label("label")
                                            .build()
                                    )
                                    .startLocation(
                                        NavigationRetrieveRouteResponse.Route.Leg.Step.StartLocation
                                            .builder()
                                            .latitude(0.0)
                                            .longitude(0.0)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .predictedDuration(0.0)
                    .rawDuration(0.0)
                    .specialObjects(JsonValue.from(mapOf<String, Any>()))
                    .startLocation(
                        NavigationRetrieveRouteResponse.Route.StartLocation.builder()
                            .latitude(0.0)
                            .longitude(0.0)
                            .build()
                    )
                    .weight(0.0)
                    .build()
            )
        assertThat(navigationRetrieveRouteResponse.status()).contains("status")
        assertThat(navigationRetrieveRouteResponse.warning().getOrNull()).containsExactly("string")
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val navigationRetrieveRouteResponse =
            NavigationRetrieveRouteResponse.builder()
                .msg("msg")
                .addRoute(
                    NavigationRetrieveRouteResponse.Route.builder()
                        .distance(0.0)
                        .distanceFull(0.0)
                        .duration(0L)
                        .endLocation(
                            NavigationRetrieveRouteResponse.Route.EndLocation.builder()
                                .latitude(0.0)
                                .longitude(0.0)
                                .build()
                        )
                        .geojson(
                            NavigationRetrieveRouteResponse.Route.Geojson.builder()
                                .geometry("geometry")
                                .properties("properties")
                                .type(NavigationRetrieveRouteResponse.Route.Geojson.Type.POINT)
                                .build()
                        )
                        .geometry("geometry")
                        .addLeg(
                            NavigationRetrieveRouteResponse.Route.Leg.builder()
                                .distance(
                                    NavigationRetrieveRouteResponse.Route.Leg.Distance.builder()
                                        .value(0L)
                                        .build()
                                )
                                .duration(
                                    NavigationRetrieveRouteResponse.Route.Leg.Duration.builder()
                                        .value(0L)
                                        .build()
                                )
                                .endLocation(
                                    NavigationRetrieveRouteResponse.Route.Leg.EndLocation.builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .rawDuration(JsonValue.from(mapOf<String, Any>()))
                                .startLocation(
                                    NavigationRetrieveRouteResponse.Route.Leg.StartLocation
                                        .builder()
                                        .latitude(0.0)
                                        .longitude(0.0)
                                        .build()
                                )
                                .addStep(
                                    NavigationRetrieveRouteResponse.Route.Leg.Step.builder()
                                        .distance(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Distance
                                                .builder()
                                                .value(0L)
                                                .build()
                                        )
                                        .drivingSide("driving_side")
                                        .duration(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Duration
                                                .builder()
                                                .value(0L)
                                                .build()
                                        )
                                        .endLocation(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .EndLocation
                                                .builder()
                                                .latitude(0.0)
                                                .longitude(0.0)
                                                .build()
                                        )
                                        .geojson(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Geojson
                                                .builder()
                                                .geometry("geometry")
                                                .type("type")
                                                .build()
                                        )
                                        .geometry("geometry")
                                        .addIntersection(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .Intersection
                                                .builder()
                                                .addBearing(0L)
                                                .addClass("string")
                                                .addEntry(true)
                                                .intersectionIn(0L)
                                                .intersectionOut(0L)
                                                .addLane(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Intersection
                                                        .Lane
                                                        .builder()
                                                        .addIndication("string")
                                                        .valid(true)
                                                        .build()
                                                )
                                                .location(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Intersection
                                                        .Location
                                                        .builder()
                                                        .latitude(0.0)
                                                        .longitude(0.0)
                                                        .name("name")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .maneuver(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step.Maneuver
                                                .builder()
                                                .bearingAfter(0.0)
                                                .bearingBefore(0.0)
                                                .coordinate(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Maneuver
                                                        .Coordinate
                                                        .builder()
                                                        .latitude(0.0)
                                                        .longitude(0.0)
                                                        .name("name")
                                                        .build()
                                                )
                                                .instruction("instruction")
                                                .maneuverType("`turn`")
                                                .muted(true)
                                                .roundaboutCount(0L)
                                                .addVoiceInstruction(
                                                    NavigationRetrieveRouteResponse.Route.Leg.Step
                                                        .Maneuver
                                                        .VoiceInstruction
                                                        .builder()
                                                        .distanceAlongGeometry(0L)
                                                        .instruction("instruction")
                                                        .unit("unit")
                                                        .build()
                                                )
                                                .build()
                                        )
                                        .name("name")
                                        .reference("reference")
                                        .roadShieldType(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .RoadShieldType
                                                .builder()
                                                .imageUrl("image_url")
                                                .label("label")
                                                .build()
                                        )
                                        .startLocation(
                                            NavigationRetrieveRouteResponse.Route.Leg.Step
                                                .StartLocation
                                                .builder()
                                                .latitude(0.0)
                                                .longitude(0.0)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .predictedDuration(0.0)
                        .rawDuration(0.0)
                        .specialObjects(JsonValue.from(mapOf<String, Any>()))
                        .startLocation(
                            NavigationRetrieveRouteResponse.Route.StartLocation.builder()
                                .latitude(0.0)
                                .longitude(0.0)
                                .build()
                        )
                        .weight(0.0)
                        .build()
                )
                .status("status")
                .addWarning("string")
                .build()

        val roundtrippedNavigationRetrieveRouteResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(navigationRetrieveRouteResponse),
                jacksonTypeRef<NavigationRetrieveRouteResponse>(),
            )

        assertThat(roundtrippedNavigationRetrieveRouteResponse)
            .isEqualTo(navigationRetrieveRouteResponse)
    }
}
