// File generated from our OpenAPI spec by Stainless.

package ai.nextbillion.models.autosuggest

import ai.nextbillion.core.JsonValue
import ai.nextbillion.core.jsonMapper
import ai.nextbillion.models.geocode.Access
import ai.nextbillion.models.geocode.Address
import ai.nextbillion.models.geocode.Categories
import ai.nextbillion.models.geocode.ContactObject
import ai.nextbillion.models.geocode.Contacts
import ai.nextbillion.models.geocode.MapView
import ai.nextbillion.models.geocode.Position
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

internal class AutosuggestSuggestResponseTest {

    @Test
    fun create() {
        val autosuggestSuggestResponse =
            AutosuggestSuggestResponse.builder()
                .addItem(
                    AutosuggestSuggestResponse.Item.builder()
                        .id("id")
                        .access(Access.builder().lat(0.0).lng(0.0).build())
                        .address(
                            Address.builder()
                                .city("city")
                                .countryCode("countryCode")
                                .countryName("countryName")
                                .county("county")
                                .district("district")
                                .houseNumber("houseNumber")
                                .label("label")
                                .postalCode("postalCode")
                                .state("state")
                                .stateCode("stateCode")
                                .street("street")
                                .build()
                        )
                        .addCategory(
                            Categories.builder().id("id").name("name").primary("primary").build()
                        )
                        .addContact(
                            Contacts.builder()
                                .addEmail(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addFax(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addMobile(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addPhone(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addTollFree(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addWww(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .distance(0L)
                        .mapView(
                            MapView.builder()
                                .east("east")
                                .north("north")
                                .south("south")
                                .west("west")
                                .build()
                        )
                        .openingHours(
                            AutosuggestSuggestResponse.Item.OpeningHours.builder()
                                .addTimeRange(
                                    AutosuggestSuggestResponse.Item.OpeningHours.TimeRange.builder()
                                        .endTime(
                                            AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                                .EndTime
                                                .builder()
                                                .date("date")
                                                .hour(0L)
                                                .minute(0L)
                                                .build()
                                        )
                                        .startTime(
                                            AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                                .StartTime
                                                .builder()
                                                .date("date")
                                                .hour(0L)
                                                .minute(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .position(Position.builder().lat("lat").lng("lng").build())
                        .scoring(
                            AutosuggestSuggestResponse.Item.Scoring.builder()
                                .fieldScore(JsonValue.from(mapOf<String, Any>()))
                                .queryScore(0.0)
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .build()

        assertThat(autosuggestSuggestResponse.items().getOrNull())
            .containsExactly(
                AutosuggestSuggestResponse.Item.builder()
                    .id("id")
                    .access(Access.builder().lat(0.0).lng(0.0).build())
                    .address(
                        Address.builder()
                            .city("city")
                            .countryCode("countryCode")
                            .countryName("countryName")
                            .county("county")
                            .district("district")
                            .houseNumber("houseNumber")
                            .label("label")
                            .postalCode("postalCode")
                            .state("state")
                            .stateCode("stateCode")
                            .street("street")
                            .build()
                    )
                    .addCategory(
                        Categories.builder().id("id").name("name").primary("primary").build()
                    )
                    .addContact(
                        Contacts.builder()
                            .addEmail(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addFax(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addMobile(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addPhone(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addTollFree(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addWww(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .distance(0L)
                    .mapView(
                        MapView.builder()
                            .east("east")
                            .north("north")
                            .south("south")
                            .west("west")
                            .build()
                    )
                    .openingHours(
                        AutosuggestSuggestResponse.Item.OpeningHours.builder()
                            .addTimeRange(
                                AutosuggestSuggestResponse.Item.OpeningHours.TimeRange.builder()
                                    .endTime(
                                        AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                            .EndTime
                                            .builder()
                                            .date("date")
                                            .hour(0L)
                                            .minute(0L)
                                            .build()
                                    )
                                    .startTime(
                                        AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                            .StartTime
                                            .builder()
                                            .date("date")
                                            .hour(0L)
                                            .minute(0L)
                                            .build()
                                    )
                                    .build()
                            )
                            .build()
                    )
                    .position(Position.builder().lat("lat").lng("lng").build())
                    .scoring(
                        AutosuggestSuggestResponse.Item.Scoring.builder()
                            .fieldScore(JsonValue.from(mapOf<String, Any>()))
                            .queryScore(0.0)
                            .build()
                    )
                    .title("title")
                    .build()
            )
    }

    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val autosuggestSuggestResponse =
            AutosuggestSuggestResponse.builder()
                .addItem(
                    AutosuggestSuggestResponse.Item.builder()
                        .id("id")
                        .access(Access.builder().lat(0.0).lng(0.0).build())
                        .address(
                            Address.builder()
                                .city("city")
                                .countryCode("countryCode")
                                .countryName("countryName")
                                .county("county")
                                .district("district")
                                .houseNumber("houseNumber")
                                .label("label")
                                .postalCode("postalCode")
                                .state("state")
                                .stateCode("stateCode")
                                .street("street")
                                .build()
                        )
                        .addCategory(
                            Categories.builder().id("id").name("name").primary("primary").build()
                        )
                        .addContact(
                            Contacts.builder()
                                .addEmail(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addFax(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addMobile(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addPhone(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addTollFree(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addWww(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .distance(0L)
                        .mapView(
                            MapView.builder()
                                .east("east")
                                .north("north")
                                .south("south")
                                .west("west")
                                .build()
                        )
                        .openingHours(
                            AutosuggestSuggestResponse.Item.OpeningHours.builder()
                                .addTimeRange(
                                    AutosuggestSuggestResponse.Item.OpeningHours.TimeRange.builder()
                                        .endTime(
                                            AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                                .EndTime
                                                .builder()
                                                .date("date")
                                                .hour(0L)
                                                .minute(0L)
                                                .build()
                                        )
                                        .startTime(
                                            AutosuggestSuggestResponse.Item.OpeningHours.TimeRange
                                                .StartTime
                                                .builder()
                                                .date("date")
                                                .hour(0L)
                                                .minute(0L)
                                                .build()
                                        )
                                        .build()
                                )
                                .build()
                        )
                        .position(Position.builder().lat("lat").lng("lng").build())
                        .scoring(
                            AutosuggestSuggestResponse.Item.Scoring.builder()
                                .fieldScore(JsonValue.from(mapOf<String, Any>()))
                                .queryScore(0.0)
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .build()

        val roundtrippedAutosuggestSuggestResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(autosuggestSuggestResponse),
                jacksonTypeRef<AutosuggestSuggestResponse>(),
            )

        assertThat(roundtrippedAutosuggestSuggestResponse).isEqualTo(autosuggestSuggestResponse)
    }
}
