// File generated from our OpenAPI spec by Stainless.

package ai.nextbillion.models.geocode

import ai.nextbillion.core.JsonValue
import ai.nextbillion.core.jsonMapper
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import kotlin.jvm.optionals.getOrNull
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Disabled
import org.junit.jupiter.api.Test

internal class GeocodeBatchCreateResponseTest {

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun create() {
        val geocodeBatchCreateResponse =
            GeocodeBatchCreateResponse.builder()
                .addItem(
                    GeocodeBatchCreateResponse.Item.builder()
                        .id("id")
                        .access(Access.builder().lat(0.0).lng(0.0).build())
                        .address(
                            Address.builder()
                                .city("city")
                                .countryCode("countryCode")
                                .countryName("countryName")
                                .county("county")
                                .district("district")
                                .houseNumber("houseNumber")
                                .label("label")
                                .postalCode("postalCode")
                                .state("state")
                                .stateCode("stateCode")
                                .street("street")
                                .build()
                        )
                        .addCategory(
                            Categories.builder().id("id").name("name").primary("primary").build()
                        )
                        .addContact(
                            Contacts.builder()
                                .addEmail(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addFax(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addMobile(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addPhone(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addTollFree(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addWww(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .distance(0L)
                        .mapView(
                            MapView.builder()
                                .east("east")
                                .north("north")
                                .south("south")
                                .west("west")
                                .build()
                        )
                        .position(Position.builder().lat("lat").lng("lng").build())
                        .scoring(
                            GeocodeBatchCreateResponse.Item.Scoring.builder()
                                .fieldScore(JsonValue.from(mapOf<String, Any>()))
                                .queryScore(0.0)
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .build()

        assertThat(geocodeBatchCreateResponse.items().getOrNull())
            .containsExactly(
                GeocodeBatchCreateResponse.Item.builder()
                    .id("id")
                    .access(Access.builder().lat(0.0).lng(0.0).build())
                    .address(
                        Address.builder()
                            .city("city")
                            .countryCode("countryCode")
                            .countryName("countryName")
                            .county("county")
                            .district("district")
                            .houseNumber("houseNumber")
                            .label("label")
                            .postalCode("postalCode")
                            .state("state")
                            .stateCode("stateCode")
                            .street("street")
                            .build()
                    )
                    .addCategory(
                        Categories.builder().id("id").name("name").primary("primary").build()
                    )
                    .addContact(
                        Contacts.builder()
                            .addEmail(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addFax(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addMobile(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addPhone(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addTollFree(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .addWww(
                                ContactObject.builder()
                                    .addCategory(ContactObject.Category.builder().id("id").build())
                                    .label("label")
                                    .value("value")
                                    .build()
                            )
                            .build()
                    )
                    .distance(0L)
                    .mapView(
                        MapView.builder()
                            .east("east")
                            .north("north")
                            .south("south")
                            .west("west")
                            .build()
                    )
                    .position(Position.builder().lat("lat").lng("lng").build())
                    .scoring(
                        GeocodeBatchCreateResponse.Item.Scoring.builder()
                            .fieldScore(JsonValue.from(mapOf<String, Any>()))
                            .queryScore(0.0)
                            .build()
                    )
                    .title("title")
                    .build()
            )
    }

    @Disabled("skipped: tests are disabled for the time being")
    @Test
    fun roundtrip() {
        val jsonMapper = jsonMapper()
        val geocodeBatchCreateResponse =
            GeocodeBatchCreateResponse.builder()
                .addItem(
                    GeocodeBatchCreateResponse.Item.builder()
                        .id("id")
                        .access(Access.builder().lat(0.0).lng(0.0).build())
                        .address(
                            Address.builder()
                                .city("city")
                                .countryCode("countryCode")
                                .countryName("countryName")
                                .county("county")
                                .district("district")
                                .houseNumber("houseNumber")
                                .label("label")
                                .postalCode("postalCode")
                                .state("state")
                                .stateCode("stateCode")
                                .street("street")
                                .build()
                        )
                        .addCategory(
                            Categories.builder().id("id").name("name").primary("primary").build()
                        )
                        .addContact(
                            Contacts.builder()
                                .addEmail(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addFax(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addMobile(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addPhone(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addTollFree(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .addWww(
                                    ContactObject.builder()
                                        .addCategory(
                                            ContactObject.Category.builder().id("id").build()
                                        )
                                        .label("label")
                                        .value("value")
                                        .build()
                                )
                                .build()
                        )
                        .distance(0L)
                        .mapView(
                            MapView.builder()
                                .east("east")
                                .north("north")
                                .south("south")
                                .west("west")
                                .build()
                        )
                        .position(Position.builder().lat("lat").lng("lng").build())
                        .scoring(
                            GeocodeBatchCreateResponse.Item.Scoring.builder()
                                .fieldScore(JsonValue.from(mapOf<String, Any>()))
                                .queryScore(0.0)
                                .build()
                        )
                        .title("title")
                        .build()
                )
                .build()

        val roundtrippedGeocodeBatchCreateResponse =
            jsonMapper.readValue(
                jsonMapper.writeValueAsString(geocodeBatchCreateResponse),
                jacksonTypeRef<GeocodeBatchCreateResponse>(),
            )

        assertThat(roundtrippedGeocodeBatchCreateResponse).isEqualTo(geocodeBatchCreateResponse)
    }
}
